---
name: Build and Test

on:
  push:
    branches:
      - master
    paths-ignore:
      - "*.md"

  pull_request:
    branches:
      - master
    paths-ignore:
      - "*.md"

  workflow_dispatch:

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    permissions:
      actions: read/write
      checks: read/write
      contents: read/write
      deployments: read/write
      id-token: read/write
      issues: read/write
      discussions: read/write
      packages: read/write
      pages: read/write
      pull-requests: read/write
      repository-projects: read/write
      security-events: read/write
      statuses: read/write

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release

      - name: Test
        run: dotnet test --collect:"XPlat Code Coverage"

      - name: Code Coverage Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: GitInsightTest/TestResults/**/coverage.cobertura.xml
          badge: true
          fail_below_min: true
          format: markdown
          hide_branch_rate: false
          hide_complexity: true
          indicators: true
          output: both
          thresholds: "60 80"

      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          recreate: true
          path: code-coverage-results.md

      - name: Write to Job Summary
        run: cat code-coverage-results.md >> $GITHUB_STEP_SUMMARY
